---
- hosts: linkedtv-dev

  vars_files:
    - "{{prudentia_dir}}/vars/global.yml"
    - ./common_vars.yml

  vars:
    - root_dir: ..

    - webserver: nginx
    - springfield_ip: 10.20.30.53
    - app_address: tkk.dev

  tasks:
    - include: "{{prudentia_dir}}/tasks/common-setup.yml"

    - include: "{{root_dir}}/components/base.yml"

    - include: "{{root_dir}}/components/springfield.yml"

    - include: "{{root_dir}}/components/server.yml"

    - include: "{{root_dir}}/components/client.yml"
