---
- hosts: linkedtv-dev

  vars_files:
    - "{{prudentia_dir}}/vars/global.yml"

  vars:
    - root_dir: ..

    - install_dir: /opt/tkk
    - install_dir_client: "{{install_dir}}/client"
    - install_dir_springfield: /opt/springfield

    - git_repository: https://github.com/TizianoPerrucci/tkk-demo.git

    - mysql_root_password: nDN8Dtp

    #- springfield_ip: 192.16.196.73
    #- app_address: pip.ia.cwi.nl

    - springfield_ip: 85.223.106.135
    - app_address: 85.223.106.135

  tasks:
    - include: "{{prudentia_dir}}/tasks/common-setup.yml"

    - include: "{{root_dir}}/components/base.yml"

    - include: "{{root_dir}}/components/springfield.yml"

    - include: "{{root_dir}}/components/server.yml"

    - include: "{{root_dir}}/components/client.yml"
