---
- hosts: linkedtv-dev

  vars_files:
    - "{{prudentia_dir}}/vars/global.yml"
    - ./common_vars.yml

  vars:
    - root_dir: ..

    - webserver: apache
    - springfield_ip: 192.16.196.73
    - app_address: pip.ia.cwi.nl

  tasks:
    - include: "{{prudentia_dir}}/tasks/common-setup.yml"

    - include: "{{root_dir}}/components/base.yml"

    - include: "{{root_dir}}/components/springfield.yml"

    - include: "{{root_dir}}/components/server.yml"

    - include: "{{root_dir}}/components/client.yml"
